### ISSUE TITLE
Extend search/filtering capabilities

### ISSUE THREAD

**Issue by davenquinn** [UW-xDD/document-store#4]
Making sure documents are searchable is a clear priority (#2), so interfaces can allow navigation between similar documents. Along with making sure xDD search APIs are easy to use with this (#3), we could also add basic filtering capabilities to this system.

Some ideas:
- Filtering by groups (i.e., import batches)
- Basic title string search

If we wanted to do this in the most basic way, we could rely on something like [Postgrest](https://postgrest.org/en/stable/) to create a filterable view of the metadata tables.

It's unclear to me how high of a priority this is, given that GeoKB and xDD will have most of the documents in this system and both have significant search capabilities.

**Comment by iross** [comment]
Long-term, yes, but I think in the immediate term, we can just lean on xDD search. I don't want to recreate too much of the core xDD search functionality in this API without a clear need.

**Comment by davenquinn** [comment]
Yeah if the integration with xDD is relatively tight, there's not much reason to go this route I think
