### ISSUE TITLE
Additional metadata fields

### ISSUE THREAD

**Issue by davenquinn** [UW-xDD/document-store#5]
It would be nice to have additional metadata about documents. Some ideas:

- Date ingested
- Batch ingested
- Page count
- Page thumbnail sizes
- Other system identifiers (e.g., GeoKB if relevant)
- Pre-constructed URLs, potentially (for ease of use)
    - DOI link
    - xDD link

It might be possible to fully rely on xDD for the metadata search and reporting (#3) in which this case some of these fields are less relevant

**Comment by iross** [comment]
date, batch name, page count, and external IDs make the most sense to me at the moment. 

@davenquinn What exactly do you mean by thumbnail sizes?

**Comment by davenquinn** [comment]
I think I just meant the width and height of images for each page; i.e. the reference frame of the page coordinate system
